trigger:
- master

variables:
  UDI_USERNAME: $(udiUser)
  UDI_PASSWORD: $(udiPass)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Username is $(UDI_USERNAME)"
      ESCAPED_PW=$(printf '%s\n' "$(UDI_PASSWORD)" | sed -e 's/[\/&]/\\&/g')
      echo "PW is $ESCAPED_PW"
      sed -e "s/%UDI_USERNAME%/$(UDI_USERNAME)/" -e "s/%UDI_PASSWORD%/$ESCAPED_PW/" check-udi.side > parsed.side
      cat parsed.side
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npx selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars, headless]" parsed.side'