trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sed -i "s%USERNAME%$USERNAME%g" "check-udi.side"
      sed -i "s%PASSWORD%$PASSWORD%g" "check-udi.side"

