trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sed -e "s/%USERNAME%/$USERNAME/" -e "s/%PASSWORD%/$PASSWORD/" check-udi.side > parsed.side
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'npx selenium-side-runner parsed.side -c "browserName=firefox"'